---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
  namespace: authelia
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia
  namespace: authelia
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:Gh+r/41bESLtZgs9r+Zzj+dy16CA71WkgvTyaRHkJfjYC92G,iv:ATt3rBY0Lnki7sn50G0hDFFkZTIJVbn6FuzsFr0v648=,tag:nEGMOvTmZgXzzuWXRH7RRw==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:2RU1wiklJmwQ6sqg7WbJdnQGP6xZHZOUonjSQ6vd,iv:rmAk8kcLODdG+GrYIXeWNjj33SqoS4v5MGZn1Ut7ZSA=,tag:Y1wCW1aApm2Biz1vPzAQvQ==,type:str]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:AR2Ed9eEB4P3nr5/GRwE96xR0u+miN5yEIANDZ44eb0=,iv:uHATogWz6XkRt3IrlAgn08bWeeFSTodhDk3swqcNlOg=,tag:7WDi/3/ehqKYtDApMHT3Tw==,type:str]
  HMAC_SECRET: ENC[AES256_GCM,data:dj5GwVhXhaSzf7L/1NhylVh66RtBi5Lgl+1Mxpsr8L3ol4kBkEROd9zLEIJz2V8uUgY6s9LlzJZOWNqDTzMi6QmbkUdYgYyCZ4UZU/5KfzQY7jg6ARbxpX3hzOhopxICb+2nw677S2bPJds6i2+pfwdzUU4W1zR7eQlAzwEg+mQ=,iv:mJSW+pngkhHoOTNzR4O4Z1begn+Tger+e3jdEr+Mjew=,tag:zxuRp/py33+LLwLJiUvrTg==,type:str]
  ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:v96CY7GeK2WLh7AxTIVg4kcbpW+0BVe9qESAJu77BKrRGAIyjF0c4RZNfMYrr57K/0k0pmeMEl11Xa4EJ3/KJtkvQmaPNumfBPe/eB/zzifltGG9BNnWfeqzXObvDZ62vyy7rWEJiTBpI/8xnVZIq0JuYGRhPNR3xUU3THDY6Zoi3vLSgXoGA2FS9/JMh8Rw0ycb/lotaTuEsNLl+lMbfdL6jqTNMfEwrhhf8JoNQTSNtfcGHpSoW8Y5gdt2w54n1aEB/SrvWJdGodJMYvxc1YNsZ+FfGOdhunmZ3dcP50ghR8FEoQxA5+e+A3+GrIRaWtoloRre8EBYsD4NnxxgbPQ7OJ4WVslv2fR3ZCssYc/MRlFNfIf3La5SecyqzC6k56R6fLXuUv6xbgA1o69TmpEdACSrLSBlY1j787QzgZrw0Jqgv4NLdVdt0TFbKTmV0dQLGVzmkZCw29wZEz7I3M7FuawWFD7/0yhHPE/P4bx9PU0c8Ut30lrcUD4JgP09CJJByhm82LhqLLR+uqijVM0OcY5yEHIu6U1EYazRw6LWZGa1oAp3UUScRWPniotS6WPdRZqiKsUlLDbsWH9G7xQ3PUZ4ZE42cVouZRki4hwhJ8l3P/64vqGcj4t4REZKi5C7hHpoRNby1OAmKK6g6iebCalz3ANEQCb5hD1tYILaECnAzJmvKhyOeVYhx+k+3byfo0GP73dfNyDzu2C1uT07JKXI8bf+Jz7pXaHJqtBYx17VmZSg/EK7lO2LXvNCGGFRgqnnFtRl/adWFY4Y+VvaARQa/tChXTM1c0yZhnJtLIoJyEQpjinLscZxju9LlrP79ubb3ljNk8TWb1UZHjhDk4j3UJ9kdPhiYay4W6dLl7UwlsMlnbUB/ZalcUKQ7Il51rbrkUYBE9pnfIkfEFRzAbzLXKARRP8NKOb57ItIrA4Lfr8ShgTOfhPxUlwFqI8/MHCF6WkFE8iFKADa+J/i/J0K12fVrbvzTuUQdEnBLzbi0+BYOGNiEYD1mtA1b8/wzWfTAqPuAU7PG4fDtBLpXEAxag2QltYKkjhWNIimqOnaDt3kJJWS+jDPp99rpv4Ya5GPy9byBvvMyqH0LVoO2TkzERjhR4t/lzp5422zsK8jFjJhbDjxOvEbKtfg/b/vjiSlIdUvbrzPl7+1MFYzG3rYkT3zaUpJYUd0RwOrP+H1QYL25Cc3kKEHZMDqp4WeTKxGzsqULIx+4nXVsN5yB4nA3oEQPiskJ4/eoD9FHNs4i5tQyLLkC42DTlrEDbXBnpNf9+KGCff29/EOyxOtml31Q6vjaQSSDG3PQ5vfdoggUo/jklWANCIztw7CMKH/ZnrdUX887TV+9Iw3dtW/WWARRqZ1jM0nSbEA6V1gmHoSld3Zm+yTVcWHsacKud/gtljhByBLrZ99SOKL2ChPn8qNhUGKFlu0PtqxLRrFRrhpq19fYWIzLDoCc9aiUfI83Obu0n/QPe4iEy3b4XWsk5BHuS/H6tvJZmYBvfJznz/Rl5ZdqcodB6fGX33fEoas773g8X6Dcl6dTd2JxsZmWcWknM/1aB91hvkCj3MIAOyQVmwcsfIE7PP+CsYiTCFonrBf76DL9O8uObxj3yqijmtORwW9Uce3WCupHlvFHbb247BUv2wOwB7lg3RpT8JKbJy8OE4S1UupSmA3pU/EBq3jWlS/dugVd0YK/I3SRvlo38XJUzzWzgr42OuIgTpkADNnipgObG6pH0oUAtvCZj1auA/Zcbagn3fmQ/0npV6PxKce++Ik7wOJBOQ49hbpQcsGxTtMXeI4WRW70Vu3N2fmGNCqqemWSRJMJTjZBHKrnarEBpLHiluKxt2ZD9Nnp6ms/rvfiEa/emZ9zdYDdfBR5COOll83FtGpi8cOk2Er3B+afUSznNnx76GYrTkDfFAkfucUetebMz3Xx0Kpi6afPvidllDlOcmAFRCt3v3b+lMBkKMTa3nFXNtWESG9GDCMhy8oUWDd67THqumF+Gq/3njPHiPI0Z6z/rtTDSJBzFedp7exHA8VtjHromwv74uzFFPMRF1+z3h96q7MBCFuxjcHD5ivb76ZmVehWgw99Z2gSCS3mL7Do3uExsroR1Y8927ox36Bd5GTKSFMJz050zFLEh+aR9J5tWAjsWv4BSVpxekFesiU6wy8kRvZgGK4Mlepdc2BBajaro8gMdc+Ea+/Ja13EfI7FcIuEe+asD15HjNuDH8KreVKqyyRP4BGuhMwxrdHXO4nEb+5z1NFx8cb1lKrwEWjibEJV8Hv6V4l4pifmWDFRuA8OEeiX+AJ72PL8eK3eqWlb33rv+kHjUiyj98bk6P4Bg7995uc5D0jIovt2fhxDLcFOEdXwMHf/1R7tdqtzFhNttmZ1KSs32geWYKqjW2DOTyjMISdCSr6LDtL7doQNrdgRYtgBDQO9fv63lU=,iv:cbZI3tYY0D0GAQH0k54B3cy2tRfUcXjNI23g4S1Dksg=,tag:JJd3gjXKYmwydFj3hBLIww==,type:str]
  JELLYFIN_CLIENT_SECRET: ENC[AES256_GCM,data:JpW397vMCs+Qmqd1UDXGxm2dF9b3ucyg8PPIlYs5AluUvvxjbbcMuME4hrASp/BNXPIPaLHfDcfZTWOVPQ50suaq7NdHDc87EA4A8rViGdKl6VU4Z/7S6v7W9RFWG8oCfDhVWaLDLlrKNCaiOdin+rbkUf/7Bx86pcUiTRbtkBT8fsw=,iv:F745LXLxIMLrW/5S84+PfCLmB6muDU/AA6gny+ESs5M=,tag:4/aQZJyRyqKQBwkLMhcC2A==,type:str]
  LINKDING_CLIENT_SECRET: ENC[AES256_GCM,data:sBal9XdVgdBNnKxhu2L3GsMe2W6dmMsV3XrnawfP6hkSq49hgVrFp/pUaGTpOV7i7zf6XHeOjqXcPSeRAmwWjYxZ5UHUducAmXRK6YIGSCMVnpKbRMYpjKixNKvBDwXPaUxMxPbQTphEOz/TO+AYA1WQZMr2x7BSEV4hUuGyPoNp23c=,iv:6MZkrMhW5C25kPFTeSn80kyH6aj3N3nHbgO+aDkkFlY=,tag:3j655t+eplYcy3q+70N9vA==,type:str]
  HOARDER_CLIENT_SECRET: ENC[AES256_GCM,data:iIPpYhlLe4qDqGDCzPUM7KvPZjbzv/uudoPyzB55kcxnCwd8YDAHDOm6R7EXxVMEFnECiPkUo65LaX3G++Z4bvX5A3CShm6Lwg6ADPd9NvIJHq3Rodm/xT8IbRyZWf5bvJLpToLSBDBAw0/il+dJ1H669wtweNsYFKtzdjMriDVYGH8=,iv:Dkza0bDvSZL1CmnLcTJANH2NhRlJk1a7EpaZ54MQ4hQ=,tag:nJeTSnq1YmkLXliF2iQDbw==,type:str]
  users.yml: ENC[AES256_GCM,data:3HtEL1TOEZw1tURjK7sI+q6gtorDVb1tAEm996pNE0vED+gaswS4WsZpRf8DvlLhNRPLRONWkbj9otnZeB+D3Ug4GWLbYlAGfOhL0VRH3yc9rFF0MJRghTXzFF0rbcOEJw6sqxPzNSUDkXrFsyxCSsG8pMv6tfsS+rGt0DH3RZ/OFqKl+inqJsXArBq3BpYxI87Rz0uITlak///LiZ9sRnSkdmwzXDk3MWWR5i8RB7fSzgWWcI3AZFMPLaJVc0pYJQ8I1pugWNBqg/6OXIrSUIIRuwhMQRUiYYLoiYapQ4YT82CeWwkeldiS9PD1K8FSdauio9mIlHL/yfiMwCCOXzv4OAJLBV20MA5cJWiAYtS8n2viBPk9AEBIkTBfUQXjBKgsWLkRqeEodlI3e2XP52111juM0m6/K9paRYi8a9Juq47osCOVJ09yYPF5mI8yuLIBwVCDaFmcL/oeoE8Rhe7zcKdXMzDNcnukPa031vlEC2k1cwRAOi57Z3yeL68mGYezVWV9sFIuLAXu5XQaAKS5/cTHmpehhdQGdJmb0M6iju/pHZLkHTQWrVfknHInC4qe99qeddM9ph0q8ukqUw1+BDV+AM98Fxlvw2qORND3BEaGGeSFLCTcKXysRweNWJxXT8EKFZlj0jNg4aJE4FTyP+bhEr+bTpjlS/XswKgDol84VCSGGNitVO59vErWJiMdB2+QdPBbNVlX7lFVj3fsUDTSZhPAhJ5KEU7O1Lj0oIOqrDS7rw6kCQPuEpqRok5aKULBNPyuZtJbzgOFIwoAsNKhkZAE9CKVEQfbMsEpohovQYjkCOM=,iv:F+pBxwwWuUxoCNxhHrb2FHBFdX8cu7kKQd5CW7uT+Es=,tag:GYUF2yADxYjcw9cBc7hQSA==,type:str]
sops:
  age:
    - recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINU5sNjVKZ09oeGZORThU
        UEtGTjZMaGRLekhGMXplNkx6eWlFZXFpTjNVCmxFQ3NSakxZNmxEQ0JWVHNNcncz
        M0lseFpRSDVMOXg2UmZZakc2aVQ1TEkKLS0tIDN3bFBHcExMRWpsdi9EOEpXOHVK
        RWtFbWRXNnZnV1Jmczg3QWxMWVFqUFkK3mISHTyB9dA5egGfxR4vDsoPjnJZPzDf
        RNnm5RIP3rzkufhwt/Ngwnf4Asxr/ct9zcuyADzDQyHykHC1vsQMlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-13T22:57:43Z"
  mac: ENC[AES256_GCM,data:i7owBFim6jBS74jXIdyPvK+dANZeJT+RHvJ7gLMiOczNc29ADJbA7emVym0guy3jMqbBOTyhGkOdGGCkXPNJj9K7ioR0p8yd/aQ5HZmSzd30bCb14Q44nk+AMDAVrfU1OdRR0rrw0kW6f7zKUVMTNmvDezLEi2nEiJWW4dIInQA=,iv:BfxCGpa667A61beRNsp0SX/FjMqEVlbpIZW2OIuGitQ=,tag:cf2TepYppFX4yCgKCmC5LA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.tpl.yml: |
    server:
      address: 0.0.0.0:9091

    log:
      level: info

    identity_validation:
      reset_password:
        jwt_secret: ${JWT_SECRET}

    authentication_backend:
      password_reset:
        disable: true
      file:
        path: /secrets/users.yml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64

    access_control:
      default_policy: one_factor
      rules:
        - domain:
            - "efym.net"
          resources:
            - "^/services"
          policy: one_factor
        - domain:
            - "efym.net"
            - "hoarder.efym.net"
            - "links.efym.net"
            - "login.efym.net"
            - "tv.efym.net"
            - "vault.efym.net"
          policy: bypass
        - domain:
            - "*"
          policy: one_factor
        - domain:
            - "actual.efym.net"
            - "adguard1.efym.net"
            - "adguard2.efym.net"
            - "backrest.efym.net"
            - "dl.efym.net"
            - "files.efym.net"
            - "grafana.efym.net"
            - "openwrt.efym.net"
            - "pinchflat.efym.net"
            - "prowlarr.efym.net"
            - "pve1.efym.net"
            - "pve2.efym.net"
            - "radarr.efym.net"
            - "shell.efym.net"
            - "sonarr.efym.net"
            - "traefik.efym.net"
            - "truenas.efym.net"
            - "wireguard.efym.net"
          subject:
            - "group:users"
          policy: deny

    session:
      name: authelia_session
      same_site: lax
      secret: ${SESSION_SECRET}
      expiration: 8h
      inactivity: 8h
      cookies:
        - domain: "efym.net"
          authelia_url: "https://login.efym.net"
          default_redirection_url: "https://efym.net"

    regulation:
      max_retries: 5
      find_time: 2m
      ban_time: 10m

    theme: dark

    storage:
      encryption_key: ${ENCRYPTION_KEY}
      local:
        path: /config/db.sqlite3

    notifier:
      filesystem:
        filename: /config/notification.txt

    identity_providers:
      oidc:
        hmac_secret: ${HMAC_SECRET}
        issuer_private_key: |
          ${ISSUER_PRIVATE_KEY}
        clients:
          - client_id: hoarder
            client_name: Hoarder
            client_secret: ${HOARDER_CLIENT_SECRET}
            public: false
            authorization_policy: one_factor
            redirect_uris:
              - https://hoarder.efym.net/api/auth/callback/custom
            scopes:
              - openid
              - profile
              - email
            consent_mode: implicit
            userinfo_signed_response_alg: none

          - client_id: jellyfin
            client_name: Jellyfin
            client_secret: ${JELLYFIN_CLIENT_SECRET}
            public: false
            authorization_policy: one_factor
            require_pkce: true
            pkce_challenge_method: S256
            redirect_uris:
              - https://tv.efym.net/sso/OID/redirect/authelia
            scopes:
              - openid
              - profile
              - groups
            consent_mode: implicit
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_post

          - client_id: linkding
            client_name: Linkding
            client_secret: ${LINKDING_CLIENT_SECRET}
            public: false
            authorization_policy: one_factor
            redirect_uris:
              - https://links.efym.net/oidc/callback/
            scopes:
              - openid
              - profile
              - groups
              - email
            consent_mode: implicit
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_post
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      containers:
      - name: authelia
        image: authelia/authelia:latest
        ports:
        - containerPort: 9091
        volumeMounts:
          - name: config
            mountPath: /config
          - name: secret-volume
            mountPath: /secrets
            readOnly: true
        env:
          - name: TZ
            value: "Europe/London"
      initContainers:
      - name: init-config
        image: debian:latest
        command:
          - sh
          - -c
          - |
              apt-get update && apt-get install -y gettext-base && \
              envsubst < /config-template/configuration.tpl.yml > /config/configuration.yml && \
              echo $?
              echo "Rendered configuration:" && cat /config/configuration.yml && \
              sleep 5
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia
                key: JWT_SECRET
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia
                key: SESSION_SECRET
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: authelia
                key: ENCRYPTION_KEY
          - name: HMAC_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia
                key: HMAC_SECRET
          - name: ISSUER_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: authelia
                key: ISSUER_PRIVATE_KEY
          - name: HOARDER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia
                key: HOARDER_CLIENT_SECRET
          - name: JELLYFIN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia
                key: JELLYFIN_CLIENT_SECRET
          - name: LINKDING_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia
                key: LINKDING_CLIENT_SECRET
        volumeMounts:
          - name: config-template
            mountPath: /config-template
          - name: config
            mountPath: /config
      volumes:
      - name: config-template
        configMap:
          name: authelia-config
          items:
            - key: configuration.tpl.yml
              path: configuration.tpl.yml
      - name: config
        emptyDir: {}
      - name: secret-volume
        secret:
          secretName: authelia
