---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: authelia
  namespace: flux-system
spec:
  url: https://authelia.github.io/chart-repository
  interval: 24h
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia
  namespace: authelia
type: Opaque
stringData:
  jwt_secret: ENC[AES256_GCM,data:pOnaMd6QOrVtUEMW/ovBEZ1O+xqm3JWTZQXo1gR0p9jep61rlGk0WKY6iWs=,iv:BDQIAo/TA1GQpYhG5Qr0zVsUR/onA0t2SejnXcycV+4=,tag:BoGq0DxJxrTgChN2EfTeDQ==,type:str]
  session_secret: ENC[AES256_GCM,data:w9YAil+NS91+EQUUtQ1Xe4j122n3rySDOCKGM1QH2E0EACSDycu+SZVyJPU=,iv:QgeOiJDZvsVQOrIkr0ibS0D8ggPJwmRgw6o6R0CbUIg=,tag:AOCUqroUnq0ZxBfTnFA+Fg==,type:str]
  encryption_key: ENC[AES256_GCM,data:yI9StCRcfgIDOAaVrsoE0QnOuueG7KRirFjfystI2nF3Ubov2bl4Wc6iM78=,iv:mbTzMaZ77BC9UNWpfmcPvT89wydT0+wAzWNWnfM7QZ8=,tag:bD0iwC2U0pOS9ESAv9q3eA==,type:str]
sops:
  age:
    - recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYjFOU0gyTkVkT2FGVUN6
        NGtKSjlGSUZlSWJVN1RCSGxjbG9lZFJ0d3hvCjFUU1IzU3E4MUdxWDFFYnZ0dWZ3
        bFBEL0ZGZjFTN0VCSXIrL0tnNTFPclkKLS0tIDV6ZHdYWVp6LzFpYUhYN0RDRWFm
        L3dPN25UUXFhU1o1ZGc2a3Y2U0tJdzAKTgwwM1mpCUnW2+yUsQ0QKpddxd1o3JLa
        ez7xCvYEYM8w8BQVL6dmNaOMu5Mq1NFccfnT9bbBRF9YQaZtczJKOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T10:13:25Z"
  mac: ENC[AES256_GCM,data:NdORR6ddq9jMUDHUVm93RvauoJhBvn9x0/PHMP5pa++Yqprn2NR3LUXMalB2fD4lFLGGIiD0AjaPhGC9jxEYFgnbYgP13O71aGVTDHjlATEc6OauNg648ancJZxEPozL4t4QCCga9DhJMxJOWBgbgULz/Byc78Qe8TIJiFOBnqE=,iv:ju7Z+DcujLHEfmusvdqLXMEokywgh2MPiKN/FgYRi0U=,tag:N9zzi9rTsqjhsgROilRVMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  namespace: authelia
data:
  configuration.yml: |
    server:
      address: 0.0.0.0:9091

    log:
      level: info

    identity_validation:
      reset_password:
        jwt_secret: ${JWT_SECRET}

    authentication_backend:
      password_reset:
        disable: true
      file:
        path: /secrets/users.yml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64

    session:
      name: authelia_session
      same_site: lax
      secret: your_session_secret_here
      expiration: 8h
      inactivity: 8h
      cookies:
        - domain: "efym.net"
          authelia_url: "https://login.efym.net"
          default_redirection_url: "https://efym.net"

    regulation:
      max_retries: 5
      find_time: 2m
      ban_time: 10m

    theme: dark

    storage:
      local:
        path: /config/db.sqlite3

    access_control:
      default_policy: one_factor
      rules:
        - domain: efym.net
          policy: one_factor
      rules:
        - domain:
            - "efym.net"
          resources:
            - "^/services"
          policy: one_factor
        - domain:
            - "efym.net"
            - "login.efym.net"
          policy: bypass
        - domain:
            - "*"
          policy: one_factor
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 1h
  chart:
    spec:
      chart: authelia
      version: "0.10.37"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    secrets:
      name: authelia
    config:
      name: authelia
      key: configuration.yml

    persistence:
      enabled: false

    ingress:
      enabled: false

    service:
      type: ClusterIP
      ports:
        http: 9091
