---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: "${METALLB_CHART_VERSION}"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    crds:
      enabled: true
    frrk8s:
      enabled: false
    speaker:
      ignoreExcludeLB: true
