---
apiVersion: v1
kind: Namespace
metadata:
  name: reflector
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: flux-system
spec:
  url: https://emberstack.github.io/helm-charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 1h
  chart:
    spec:
      chart: reflector
      version: 9.1.17
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  values: {}
