kind: Secret
apiVersion: v1
metadata:
    name: authelia
    namespace: authelia
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:IhDBfLnivCMifccSBcZsV00tbwMznY8Km9oGqFGclxSk+N4k,iv:x3+f0lMoRCvC7AAeecncMSazoz+PA0ItIlTTZrIFFA8=,tag:8v9a3/JJwwe9SbpBuDYCig==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:I6czxP0PLYOo7MRD+G8I0VcGGfAnYx03WM9LsKWS,iv:3v7Wmdi4NkT9V+3HGePK3aCQzHQvZ9GzW4g4UeW97NQ=,tag:3d+IR+fqu+WW/QkNnt1WaQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:o/N0ueAUyQWDUoL8hPLd5g8e9svr3xF+sd102houGeA=,iv:RiwwQFKtQXuQc9mUtP5JVyTvsrscEGoGIxQ9IdV/mN8=,tag:EeQHieu+nZzKZMKUkuoqEw==,type:str]
    HMAC_SECRET: ENC[AES256_GCM,data:RHvBUpp2lzXvmS2S5VLZC3Gu9dFwQXy8I7Lpoz4imedT7iUcrrIDrpADy2NYqCmNY0EkDUWCJYn8M/pauCDsKWpzcU2OONBSrUvdL5wfOdwL1vDmmybhSSdpdZdav1iPRa9eWyzJwlgSxRuBw+0pK29BuKQ7bATmUOw7qVccLkw=,iv:8/1ErSjd2aCIc3qVsW5viWnkhzY3uyuyYloqUePWeQQ=,tag:uhQJlOzX8LMgadqX8JWgWQ==,type:str]
    ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:E42wedKZOTP+/QLRhHQKCJbMDAQTY3075wC/HcZ86EwDYZ/m+asjdRoLJcJ6wOWN8cVFQTeGB8lpjyPgBIhoXs041Z0XX+sZuaEwEC1wn8LUOG8kbQrue6bI457FqX+u490bjz4d8ro9r/YwTTv/g1yVQvYe9D3KxpupQ21gQ4vCIHRcY/LitGT+Db20ISiWR3lpcrohso2e6Peouz20XzKEdF1MrdYRAk5D63+7dZCtWFm6VWAuX7nhxSbBmMlZ4RksRLOgjBIObw2cl0taYgJ2vHbLHAcuICsOvhryArzqr3K9csoB8YLDF+eg8YdoqFexubm0t+TOT5FRULBDwZFlQ9n/2G+Yfweq2hr4y8/ZMzGYHImT+Pohhlkk4PkO7wjRFNc0cHwt9jhGqWHs3S7C8IqNGwRKYwfEZ6S3aFBZmDP6D8GxIXGFnkBnamfJz5pW1gGojpDPoY+8h5rt8DvZG++ZReaLAPILS9boPRrmuL0SAb6QlMzJxVSX6ylZPMHKgzAN4RLifYHQFVwr2xl7dpecMhMqSAjWyekT/yBuFVzXXxHlWp+9lJMxIBA/Xvcu2ngB+kezUL6Lb90Hq4mEMJER8TrGZzibCCZ1ohFJAqlmjQmRNHZAjtB8lhhsZFcOoNOaACdeEOl9Wqse3G+LZcMvMoETbuTqvG3kusXt7hq0+JSeQ0iBAJAzQYMFHOzkACz3UvBzF/l3dzJyLieYI4H2/3tDGZ5ENY99DxuSu4TK4T7Yj02yeinTJ5xusuzYzkfVlj9WnWsGFccPcrY2k1edGM45Tg8fyUzCpEuRETtzu7cqAzToJkAFApLzcOaKZ+UeTcE+9yZqaEvZr/SBK3y2R5ZdRzIcQ/hgwVvB0EY0SafyyCZh2ZFx55Rqv57rMqGptnt24IRAB+xNTAAIu6DcpYTuKNMSGW/mTezbI/ikhta58qA9mVT1pzwQKE6p25VrVhERDGXhG8YReNsTZIwL9hEOCUL+BIWiuMNKQS2BZ3+PIyekYCOvmiOB52o/rRRab+pRd6KuJ7coj9/inRHcG09qMkgOfEebZC7q1hzBzbXhU3uLJezg2sG7mmuu7ZA/molQCpbaUhUn1tGIFt1GFbTXki17syW0IbAyitZPOHslhcgFBgzZWfpiL/mfyf22Rbj5/qFbNjFZj7YyhTwYfuxbNWSX35pAprB+5C+Ig0mDcrL1Imyxpm5/27fxfRLBFTQzwCwom1TPMausIoCiXCUbpPPSORY/b0cxjQz5OzNiZpTkNggr/97ANBeEt/F4T7EUsQaJ09pSvX/iv3IuqE2JQeRcbX40wW5Evq0KGuD4nM/T54tJohZOv7wXbbvE1llgc+X4APl7gVOz5sCYgOHm1EK2AIxm8ZMnRCGofq8968OSGlaMz9PKgh48D48epPVwh9H2T4wwHalirapWMbHOoLGwCLt5hrpwkw83YYklQKEdVgguVh9RW36FqGOU2y40Mjz5MDSGQ6yJbDog7OE8mW8AmYFir03Y5T5KXIR1uI2eOHjAPLeLZWIsPzKCVE49xwIoBwqatNv4HU72LlWPSA6+yRZCpObahjSz0bcW7N8/pjoVigpZhEMI1U+osgtpsX6wLMkOnSTzLhsAyD3XW90gtoHx6X5zQyz9xATfAhM/qu26H9KA49ZiKiAhYqDIRuTIJSspUF/v2puXnZf935HWv58O+ypSJMky1iWyDBQkKTuhK/i5k2flhFB+coTfoFfbyBZJ0YQYNxkwlMwJA8ZGyZG8r1/QHyM9oZ0OIhiKHTrnx7+nM/eewd/j94cwZmDu56QSc4PS2hKPckRB1lIypTshP/GmF1TE3mxt7fOvRIB//n0P/vgErBiKseEeCUbIZdhfGk69NA1KyjW2Ot8trXO2vLm9A40zlKUCyM+JcjemwEX3C4KIszVVhL0CerYZvnqQVplnS1xfX9/IMoCa5RJBXoZ6hGO0NGl/cBJnz1v9x+DOs/Hrgy+Nqb6wFfit2jHfTtzBWCCzSwnEVoEuuF7jGkYyNGbC68p9dc1o5QcYFxDySpbm0LkF2w5zcmVw7lb6/lEfIpbY2LX5HYpcuV5+SuqcklsJPBJv+2zHgkG1jRkzzPkL7CNQRq9J8ZBvdEmySce10oX7YqBGCrwbUcRBS68G3Py5BCda2YDWKa3XKNaTovwrYK1WSTdOtuHpZ9KNffg5gn4LBk77KWzlbTDdbXB74rWRSQTFKeTXTPTngUc=,iv:hUngn5BNpvdLGgNlJhWYIho+IK5yyYKYHQNu9b5Jewo=,tag:IfWJV6ODgA++l1aOAMMQHA==,type:str]
    JELLYFIN_CLIENT_SECRET: ENC[AES256_GCM,data:e2FBp2hjgJvlrlKb+Rt6zUmSEi0Dz4ApIpcLN86iTTvD5VGsx3NpLVdPwYflBvjc42q/+NEmLT9IIkuhCbRQqtHHzKbKxeRDVZLMEfMoXS2mthhyb6x6BYbCPsHQqaAE+JH2qUy3D4urxm9aFRP8h9ByTwChM11jSRZNUKpiEFYLBdU=,iv:ULFDrMpaHDsr3iiih3Fcz7Z/d7tofx2zYyg5vP9i7Jw=,tag:/2qno12lPYTAOmJTK+tufg==,type:str]
    KARAKEEP_CLIENT_SECRET: ENC[AES256_GCM,data:G98OXfp+dr+/bCLNNRu+3M+eGOCtnlRFjEO8/KP6OHbYz3k8oz9u9Axj8ANyta1wMSAJPeU1OKL8vsDjM90ggKKujno3Dd6+oyQXWZGk+xi/so1lwtmTVSueSVCi3ACcQ/R5OrmGyT91vImO6BqK20srQ3waXcYpQsUty2/muxkqTE4=,iv:g47nCG5R3bVzfTNLKYPfZQ8FZSueB7G+6RwMD3NuBT4=,tag:RtmX6X/wzmq5SdVm7MfhxQ==,type:str]
    users.yml: ENC[AES256_GCM,data:/GNAY3KUOt8L+Ghg5qMw8KpEWjfBBw6AHlGJsafgAKnjgxTdRII6FhGayjLnFYWVRJQwt5jp4NDVg4Ffn+8Nga0cvwmeMyFFrBAmRzNXbcgOq3juK3RiJhVwkIxnzWaGHIysP0NLdvMpIeJHr89C4IYkTrSRmlh6/TGtWU0D2zG3K9NCGRP14sTKriD5PWpvDnia5IqJMla/vPVNcPCWilsXM+L5UzZ/pRiqgbnGcSxwwuGbn3nb0K/eA0vdmNAVOXQAX3YSYDcLkGU8ItkzAL7E,iv:VZpjBkSGPbnU/MaiCGQ7jTErOuj8OBo+/yRh6fiamcI=,tag:IYD2HgtaBB4dBKrRL+ar4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dk4xbGFieTFlNTR3a0FI
            K0ZScUJUdVVYajR0d3UvL2VjYWp0dU1RazFvCmxsbm01YnV0b29UOURPa0dFVjZ4
            aGx4QXJ2azdBN25ka3VwRTJxSmdoYU0KLS0tIE5tblV5NjJXUFlXK24rbmlXeXJV
            V3NSeEJKRHB5bXU4bEIwUFdUZkpBWVUKFGwcXUWBaLC/rliC8dcCQ94jbh9wqWu1
            Cj4e7J4N4SxZaFe29+UxmznNiwMhLXUQSBNewr98rjcSgQBg7HLzGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T16:34:27Z"
    mac: ENC[AES256_GCM,data:xHK7JNox/Ta5R4WxLil8EFsEj6WS+7irbaaNhLS3PhDJ17fWlOIpMt0b3sVzV2/24+GK9NTGETuHvPq1RduqRJ6B0drsFnY9mq1ySp1goOUPaAv0wXY7NeIhAOm1vxU/twBD70hFjmriE5ynhF7QlOHCVWCWYBaBkKvqMEyYbZc=,iv:v599mGlU+ZUHgouXc9l1QV+gmB+LDCCZv1lSD767jaE=,tag:zNxwqNTnvIbl77w2E3FdEA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:zzoc4SBBcIR3IJ4PqHFp7vsoYieUYIU4MIXmpPvG9/kxhMMGE27+TA==,iv:LvPj8m4MUUTsmRYBtE+IXlFhJmlohMR2hPRXgD4keek=,tag:JuOsQEnSg3zJKNijUu+JBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dk4xbGFieTFlNTR3a0FI
            K0ZScUJUdVVYajR0d3UvL2VjYWp0dU1RazFvCmxsbm01YnV0b29UOURPa0dFVjZ4
            aGx4QXJ2azdBN25ka3VwRTJxSmdoYU0KLS0tIE5tblV5NjJXUFlXK24rbmlXeXJV
            V3NSeEJKRHB5bXU4bEIwUFdUZkpBWVUKFGwcXUWBaLC/rliC8dcCQ94jbh9wqWu1
            Cj4e7J4N4SxZaFe29+UxmznNiwMhLXUQSBNewr98rjcSgQBg7HLzGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T16:34:27Z"
    mac: ENC[AES256_GCM,data:xHK7JNox/Ta5R4WxLil8EFsEj6WS+7irbaaNhLS3PhDJ17fWlOIpMt0b3sVzV2/24+GK9NTGETuHvPq1RduqRJ6B0drsFnY9mq1ySp1goOUPaAv0wXY7NeIhAOm1vxU/twBD70hFjmriE5ynhF7QlOHCVWCWYBaBkKvqMEyYbZc=,iv:v599mGlU+ZUHgouXc9l1QV+gmB+LDCCZv1lSD767jaE=,tag:zNxwqNTnvIbl77w2E3FdEA==,type:str]
    version: 3.13.3
