---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  url: https://helm.traefik.io/traefik
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m0s
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: "36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
    deployment:
      replicas: 3
    ports:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: "https"
            permanent: true
      websecure:
        http3:
          enabled: true
        advertisedPort: 4443
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.5.50
    rbac:
      enabled: true
