---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: linkding-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-fea54e45-0d7c-4bbe-a77f-fd8739c42fe6
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
