---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: linkding-data
spec:
  accessModes:
    - ReadWriteOnce
  # volumeName: xxxxxxxxxxx
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
