---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/movies
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.1
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-tv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/tv
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.1
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-channels
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/channels
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.1
