---
apiVersion: v1
kind: Service
metadata:
  name: openwrt
  namespace: traefik
spec:
  type: ExternalName
  externalName: quack.lan
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwrt
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openwrt.efym.net`)
      kind: Rule
      # middlewares:
      #   - name: authelia
      #     namespace: authelia
      services:
        - name: openwrt
          port: 80
  tls:
    secretName: efym-net-tls
