---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hoarder-data-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
