---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authelia-pvc
  namespace: authelia
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
