---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: monitoring

resources:
  - namespace.yaml
  - ingress.yaml
  # - sealedsecret.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values.yaml
