---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vaultwarden-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/vaultwarden/data
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
