kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://codeberg.org/tw1zr/lab
        revision: HEAD
        directories:
          - path: kubernetes/*
            exclude:
              - kubernetes/prowlarr
              - kubernetes/qbittorrent
              - kubernetes/radarr
              - kubernetes/sonarr
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://codeberg.org/tw1zr/lab
        targetRevision: HEAD
        path: 'kubernetes/{{ path.basename }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
