---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  - apps.yaml

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: argocd-server
      namespace: argocd
