---
apiVersion: v1
kind: Service
metadata:
  name: pve
  namespace: traefik
spec:
  type: ExternalName
  externalName: hades.lan
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.efym.net`)
      kind: Rule
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: pve
          port: 8006
  tls:
    secretName: efym-net-tls
