---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:+mo3yamxsLMBEe3osRirX/hIvZpX0mprhkmFcwhDOhlHphZN9kbc3A==,iv:oHJ1Plbl4w90gnth41gx1LprtcHHbckKTfDf+0+AZug=,tag:tzbtUbGVpBqUAjMuZA7cSw==,type:str]
sops:
    age:
        - recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcDM2NzVIbXo0Lzh1YWl3
            VVBDM2puWmxqdkxwZGxBQU82WVMvckRpWXhJCjBEeTN1bHV2SXBCdDZudVF3T21r
            Zlh5dWZmaDZMbHdaYXkrdEVaaDFsVzAKLS0tIFEvNjlVSlZPUVJXVnp6SjBvZEJ6
            YnJjR0JnMmFiY2dOVlNoOWtPKzhwQzQKx4CRK77L8649on3zI90WqNmxqmX36kty
            xX/AgULPwHSJkfU9xSCzvdUIKkzPX7IekGL5u3MSHoG9Nv4Evw2JBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T10:21:48Z"
    mac: ENC[AES256_GCM,data:QCAjKDqqpZy4qVM8W/+RgnAlbpn+XjEbli30ZJIe+nNdIor2x5adB2Ct/bgEg7Gs/XAWDWIIw2dqzp5pPgGlIgy+77aaSxkvk0Cu7kiLZoMn49oCHsiT+mrzr6i4vg1QIehNoWGWWKzIlEfRGciamPt5uUxTFvhuvETsJqc25F8=,iv:bZVKFqG9OsV6G59Fs9s0pm11v6emuYws446AXNXiXnA=,tag:+7Oh5CtZzmo02BH5GPnmMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
