---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: actual-budget-data-pvc
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
