---
kind: Service
apiVersion: v1
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  selector:
    app: actual-budget
  ports:
  - name: http
    port: 5006
    targetPort: 5006
    protocol: TCP
