---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pinchflat-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/pinchflat/data
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pinchflat-channels-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/channels
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
