---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pinchflat-data-pvc
  namespace: pinchflat
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pinchflat-channels-pvc
  namespace: pinchflat
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
