---
kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tw1zr@efym.net
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: tw1zr@efym.net
            apiTokenSecretRef:
              name: cloudflare
              key: cloudflare-token
        selector:
          dnsZones:
            - "efym.net"
