---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      enableServiceLinks: true
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.12.7
        ports:
          - containerPort: 7700
            name: http
        env:
          - name: MEILI_NO_ANALYTICS
            value: "true"
        volumeMounts:
          - name: meilisearch-data
            mountPath: /meili_data
      volumes:
      - name: meilisearch-data
        persistentVolumeClaim:
          claimName: meilisearch-data
