---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hoarder-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-f1e645f7-68de-4a2a-83c2-f5a74ba48597
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
