---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meilisearch-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-d413eae0-7d99-4a2b-9dbd-a82898f22160
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
