---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: filebrowser-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/filebrowser/data
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: filebrowser-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/filebrowser/config
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
