---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://codeberg.org/tw1zr/lab
    path: kubernetes/monitoring
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
