---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pinchflat
  namespace: argocd
spec:
  destination:
    namespace: pinchflat
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://codeberg.org/tw1zr/lab
    path: kubernetes/pinchflat
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
