---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backrest-userdata
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/backups
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
