---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backrest-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-a5b65cf7-cf0f-4068-b2ca-27dc7da335da
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backrest-config
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-b0b85ed7-1b45-4f3b-9571-17c3b866be4f
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backrest-userdata
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: backrest-userdata
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
