---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-quantum-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-quantum-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: filebrowser-quantum-data
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
