apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingress.yaml
  - hosts/adguard.efym.net.yaml
  - hosts/openwrt.efym.net.yaml
  - hosts/pve.efym.net.yaml
  - hosts/truenas.efym.net.yaml
