---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: actual-budget-data-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/actual-budget/data
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
