---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: actual-budget-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
