---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pinchflat-channels
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/channels
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
