---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pinchflat-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-fb97f9d2-60c4-459d-9997-1763d5479454
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pinchflat-channels
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pinchflat-channels
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
