---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: linkding-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
