---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      containers:
      - name: authelia
        image: authelia/authelia:latest
        ports:
        - containerPort: 9091
        volumeMounts:
          - name: authelia-config
            mountPath: /config
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
        env:
          - name: TZ
            value: "Europe/London"
          - name: AUTHELIA_JWT_SECRET_FILE
            value: "/app/secrets/JWT_SECRET"
          - name: AUTHELIA_SESSION_SECRET_FILE
            value: "/app/secrets/SESSION_SECRET"
          - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
            value: "/app/secrets/ENCRYPTION_KEY"
          - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
            value: "/app/secrets/HMAC_SECRET"
          - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
            value: "/app/secrets/ISSUER_PRIVATE_KEY"
          # clients
          - name: AUTHELIA_PORTAINER_CLIENT_SECRET_FILE
            value: "/app/secrets/PORTAINER_CLIENT_SECRET"
          - name: AUTHELIA_JELLYFIN_CLIENT_SECRET_FILE
            value: "/app/secrets/JELLYFIN_CLIENT_SECRET"
          - name: AUTHELIA_LINKDING_CLIENT_SECRET_FILE
            value: "/app/secrets/LINKDING_CLIENT_SECRET"
          - name: AUTHELIA_HOARDER_CLIENT_SECRET_FILE
            value: "/app/secrets/HOARDER_CLIENT_SECRET"
      volumes:
      - name: authelia-config
        configMap:
          name: authelia-config
      - name: secrets
        secret:
          secretName: authelia-secret
          items:
            - key: JWT_SECRET
              path: JWT_SECRET
            - key: SESSION_SECRET
              path: SESSION_SECRET
            - key: ENCRYPTION_KEY
              path: ENCRYPTION_KEY
            - key: HMAC_SECRET
              path: HMAC_SECRET
            - key: ISSUER_PRIVATE_KEY
              path: ISSUER_PRIVATE_KEY
            - key: PORTAINER_CLIENT_SECRET
              path: PORTAINER_CLIENT_SECRET
            - key: JELLYFIN_CLIENT_SECRET
              path: JELLYFIN_CLIENT_SECRET
            - key: LINKDING_CLIENT_SECRET
              path: LINKDING_CLIENT_SECRET
            - key: HOARDER_CLIENT_SECRET
              path: HOARDER_CLIENT_SECRET
            - key: users.yml
              path: users.yml
