---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      containers:
      - name: authelia
        image: authelia/authelia:latest
        ports:
        - containerPort: 9091
        volumeMounts:
          - name: config
            mountPath: /config
          - name: secret-volume
            mountPath: /secrets
            readOnly: true
        env:
          - name: TZ
            value: "Europe/London"
      initContainers:
      - name: init-config
        image: alpine:latest
        command:
          - sh
          - -c
          - >
            envsubst < /config-template/configuration.tpl.yml > /config/configuration.yml
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: JWT_SECRET
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: SESSION_SECRET
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: ENCRYPTION_KEY
          - name: HMAC_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: HMAC_SECRET
          - name: ISSUER_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: ISSUER_PRIVATE_KEY
          - name: PORTAINER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: PORTAINER_CLIENT_SECRET
          - name: JELLYFIN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: JELLYFIN_CLIENT_SECRET
          - name: LINKDING_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: LINKDING_CLIENT_SECRET
          - name: HOARDER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: HOARDER_CLIENT_SECRET
        volumeMounts:
          - name: config-template
            mountPath: /config-template
          - name: config
            mountPath: /config
      volumes:
      - name: config-template
        configMap:
          name: authelia-config
          items:
            - key: configuration.tpl.yml
              path: configuration.tpl.yml
      - name: config
        emptyDir: {}
      - name: secret-volume
        secret:
          secretName: authelia-secret
