---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: authelia

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml
