---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-data-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
