---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: filestash-data-pvc
  namespace: filestash
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
