apiVersion: v1
kind: Secret
metadata:
    name: volsync-credentials
    namespace: flux-system
type: Opaque
stringData:
    B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:fhdh2Zjv36NVgtjC/0FjbzgX3DBtt8DlAQ==,iv:pdrFs0ySh6tjNhONqXHOF653a2Nou/PRyuzv6G+dRtY=,tag:VFmly+tuewCLBjkSrwFqNA==,type:str]
    B2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:j0B8/g1xrbL0t4yTB34GR0b8SGnJ7hr6JJ/2KXwaUg==,iv:6kVS13NlcM0+qO6eTiOrtmcUgD9thnXRG2LOvHfAb2k=,tag:Kkikb9bXkCcoKjG6MQudgg==,type:str]
    B2_REGION: ENC[AES256_GCM,data:ogYlrC0InyThoNbIyBQ=,iv:ebFd+1/ADesWVw2HWcGEFED+IgXV/Eyyo5DfA/9K+JY=,tag:JEkNpN73tQ1tLdcBcVbJDQ==,type:str]
    RESTIC_PASSWORD_KARAKEEP_DATA: ENC[AES256_GCM,data:nkL/ITI24BAcEzJ34EFdB2IBBtfHRKbjaeDKcSzXhuSPbq/A7fzCsezAVkK5Tm7UbmJX++uvuFk0p1nLY240RA==,iv:UYxpJNZ6Yegnl92RzH7r4peHPHGsHePsAfmwQjmR4j0=,tag:fbv3U3haBJ2xjqkUxeciOA==,type:str]
    RESTIC_PASSWORD_MEILISEARCH_DATA: ENC[AES256_GCM,data:FvyINr9z4PwRdevSHLF7VOW/VeHMleqUsnudTm5IsFZtpEeQjf8H07ryepNYn1Gv4HpyYKu0LQfZr45C/2D3tA==,iv:8HFY+nkQBvtsR6RfzfHIjs1OFwywHQ7hbfCXm1K/S7g=,tag:RZsq0MpMfRjMhb+gmWrAnw==,type:str]
    RESTIC_PASSWORD_FILEBROWSER_QUANTUM_CONFIG: ENC[AES256_GCM,data:61RjovLaJiSyHpGtWVIPiWznUwOI+2WzBY29RzbZx3BWEWIdYW/DGk5gTcstQcOl3/FEMuZP9LINSSYG7NHjgg==,iv:M27lAR6v0JBhRGP2UhWjKCvl58Xf91W4Pi2a+rs4HLI=,tag:SRMJXjkY4B7JYvxocUe3jg==,type:str]
    RESTIC_PASSWORD_QBITTORRENT_DATA: ENC[AES256_GCM,data:G3F6mYJiTqdZsyPVPfEtU3aBx9LlS2BMiTtbFW0wNq7Ctx5e/K7TvDAjLaL4Pj9IaStIXCsE7dfXJWluB0iJKA==,iv:pjgqC27nVG2h+Ke4z0+8GpEUKllb2eHaUN3EuYrVm/k=,tag:niL+ld4WjqNcIyswy1p7gg==,type:str]
    RESTIC_PASSWORD_JELLYFIN_DATA: ENC[AES256_GCM,data:yIlfNBVQhbAo/oxJuRISVY713AUi0BGCXNbpkgESmkSVYrQGwfN3gGBFr988WRANM5C0Qx/zl1eiClNVgB+NTA==,iv:xyr9tQRP196WaPBVy7+jIiSv/eT+/3Wk81UMJQek3pU=,tag:d7BIRipdaEp0wC5V/WNMOA==,type:str]
    RESTIC_PASSWORD_PROWLARR_DATA: ENC[AES256_GCM,data:0KGV3TkHT0jAwkf/59YufRSUpDaZRLLmNsC/99Iw6tP4mA0/MxCR4z+cJS1Ya9hmrUnJO51fnnJAzwDAj8HCSA==,iv:smlkD2NZzTUxBnrR7yislDLIYVNfeomky+Hy3RUmAb8=,tag:z42uJ104TDlgiLrU4V9W0A==,type:str]
    RESTIC_PASSWORD_SONARR_DATA: ENC[AES256_GCM,data:qVgf06awZkNwb+5jJQkI528KGpcjid447t0nizAufC0GBY5a07hCNhDFANq8Nb1ye3z/JI3zk+dWwulToI0Uew==,iv:5yOnAxV3BK0KrUwaCDNtZhz4KGkERqXe6/mAtVFqQIc=,tag:rekz7jpVOdOSInmKp9H6/A==,type:str]
    RESTIC_PASSWORD_RADARR_DATA: ENC[AES256_GCM,data:Gm8akXdE58A5ZPrxyRovqFiD5VjnZamI7r/oCr7DDaKx4KYHlrgCF6POvQGtWr0Dage/H0W9idcleeb/v2O2tg==,iv:WVSipH0M7AXumKusIdA8IwXFDZOpyVUJDHP4qCaTcpM=,tag:80W698ORhU0FWj3fc3UhIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY2NUenFpdVpIUlhQOXhs
            ZXpoRGhScVlQZHNGdTBhSGF3SExWVDlsemc0Cmg0NWdPVXFPcGFRV2FreHhoMUFS
            N2hUWU5vRVYvc3ZSVm1KUExHK0xtWGMKLS0tIGRuZCtDQmM2b0FBWG5GQ2VNb21Y
            L1dJS1lTVElCeVptdHJKRzc1cnQ2SUUKtNh8Oww0Fw6Z7FjGADrDM3oASpTIvbX5
            Sal/c7xQVo1F0T8ZTDjqDi582X2MCtOzChiQniZUoOQqMwd/12TzdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T22:59:38Z"
    mac: ENC[AES256_GCM,data:T8jBdT7k3Y5RPeAp9VpiQKT+D62VEsZhuxGte4vf72ImfX8Sr9RBSkSOTMbo/c73t3LIucoRkqGzghWgOYQBEYEBaGylwmYNQ7ezTWJ2ohmamnsCDa5ZvcZTdwLtR9iQzquvMwTz04yg270CdXnHvGge+50l5mTFqM4O0idXHXg=,iv:o/edwDCpBQHM8yzQVfsDQnmNp1kIr9oGc4/5gxDATR8=,tag:yWDIx0Fuk6XVl30j2n5mxw==,type:str]
    version: 3.13.3
