---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-data-pvc
spec:
  volumeName: prowlarr-data-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
