kind: Secret
apiVersion: v1
metadata:
    name: hoarder-secret
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:hP5MXZtAulBu5pzuygcpF0rcsaHB1Gb1E5R4iiopnb95xFPeAbkUcA/6OA9D0N8i,iv:qPK25ZR/XB4Z1g1uvnLiB6vKfiftcF3lSce/Ikfw/p4=,tag:1JX57IAKZKZLV3kjSDKTuA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:a6T/bz3WdGyYlILaNQWeQHlZ9iRGeVXdxN3DXbe3f+w43DYB/0bM7UwvXURXVoHO,iv:cdjm64oqtSH1aLCGEcFjf8ifS7mb8FJ9jH35qqrqvNc=,tag:l29KPdq1ibvepumKsifz9w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:+VGSJZAdKvYu9t0NvJAnBEX76htx+KI5t9BXZmAfgfDDsofVbbGsRereClAwJ2AyOsts6I0iP4ADTF/+s0Zz+xCMSWalVDRB3QGKu7/aV2XXsbGFjW6dXMx5FtpcbgxXaHMBq568yPoUYOMSdwvaTCg1laJhXQ6eBA3QQl3fkvU91E1lVDr3pNF+XDMi8eCeUHRKoLJJQzzVjsFkkv2xPxmcdZ0=,iv:56JFLEUipjjzMSUodCWG/vgZRoqMCQGRq8mu458eCsg=,tag:eG4mwYRDqsjBwdsvPFfTUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgp7yrldpcpv47ra7rm6mwsn0vn3chvt7a4x2a4pnnvdfruujqtqc36q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eC9tYlB0eksrZXZKU28y
            OElaVm9IbENwRUdGZGxOZkp1MmxockZPUFI4CjhmM2NrbjcvUm9pT2lJS29UeSts
            ZXc5d2dKYTlZT0JKNnV3SmJnRmlIU28KLS0tIFNsR3RKK1dnN2MxK1NWUW1LRlFO
            SWh1ZEFLMXZiRzVvamxXVnBSMVJsMmMK2/KEe5bsCnU+ln5DO/piU4Qacy00mDIL
            y3fSMQM7qUpS0t5k+776jNX1V/gW/CA8vpggFs7o4OppaPZVJ3x15Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T22:53:39Z"
    mac: ENC[AES256_GCM,data:tLUcB+aW6M16APs4LueDmzOJdloEhZSy5ED/WgjvTGx8xRkirNT+P5K64ayV2JASsAy5And35UhezelQdMdHBX4siTQ+aS6rFc4v90j4w2XS0f5WBNc6sOew5EU1K2EwJiBUAr6pFu0Khe96P9YEXOuhnWokKB2XTJoGQjAgGpU=,iv:WHyRnRP0ImQNnlBxJH5yKDKrJvbbBr1SfUYWIwM66ec=,tag:pymOO31TAuyec61Y9t2ELA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
