---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kubernetes/cert-manager/config"
  prune: true
  timeout: 1m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: flux-system
