---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kanidm
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kubernetes/kanidm"
  prune: true
  timeout: 2m0s
  dependsOn:
    - name: flux-system
    - name: traefik-config
    - name: cert-manager-config
    - name: longhorn-chart
