---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kubernetes/longhorn/config"
  prune: true
  timeout: 1m0s
  dependsOn:
    - name: longhorn-chart
