---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./kubernetes/openebs/chart"
  prune: true
  timeout: 2m0s
  dependsOn:
    - name: flux-system
