---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: filestash-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-dffb96f9-59d3-4c5b-885c-22c-b73d0ed7
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
