---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 10m0s
  install:
    createNamespace: true
  chart:
    spec:
      chart: reflector
      version: 9.1.17
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  values: {}
