---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: radarr-movies
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/movies
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: radarr-downloads
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/downloads
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
