---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-movies
spec:
  volumeName: radarr-movies
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-downloads
spec:
  volumeName: radarr-downloads
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
