apiVersion: v1
kind: Secret
metadata:
    name: volsync-karakeep-data
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Rp/zAgXcAp0jMUdOQIkH39BwXzabAj4taisUBcIq5dmLIsXdp4UnxNH7At0HqXzHH+eT8T3fzNLN+eszq3xQ91++aQp2eGA9DhPn0Tn4Dely+gbI,iv:hZUzebrir03N7+3Civ+2MEPx4ecRGLspBb51JunCuCk=,tag:Rk+WjAzdCtN6U+KoWGLiOw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:2xUVSfJUt7zRAt6+Dsevy3Qq3mbpSNEL8PAT45eyriQ5QCz5STzhp1EwdK8S1Bh00ELNk2D/i6cS/NMMwXr4lQ==,iv:2RFjWRx07K/eLvyvtzBJxUG6YpN6fjop9iiwmnzpam0=,tag:PHkiAFpQ07YBsMbYsHTNkA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Orlnw8JrBC30LygqSheqAY6FE4nSrkSMBg==,iv:C6JFHHOQQQnbVjgySpTbHQ9Knc3w6Rm1D34vbt51EJ4=,tag:+TxvHQ+e0QE3UvWkNIrq5A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3tWyuNmk6HP4GGp8LHBkt4Y51seSViyx2yoguI/KBw==,iv:V1d01IkTqdrAWQ3FXewq/6f1tjYzx83dOHCxifRjt+k=,tag:1gytARetfBZElPn7A7KFqg==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:j/VeVfTqZAQOHoIpxo4=,iv:sgeyEmQKEnk/GxdqlKm1nQoRHxUVgrCbq9dh2mh36YI=,tag:o8bxMocwxbSLWjwrIzFVAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1lGeFBwZDl6TmJMN0dC
            akxpWVYySVFaQVJUeloyam9LRnU2Wm1rMm5rCmpFS2crcFQ3OWQrM05JQlZ2SXJB
            eHEyRy9jcDlKeVhrWlVLRmkxUzNsbHcKLS0tIHREZ0huTnlPM2haaGUwanhxY0FO
            SURSU1pndlNqT3RlUWNyOEJkU002T1EK6H8+xHpp5x4KQF6Grz2nAF5pM+Ticj8h
            7rb9kmvsBOJsBEHhyRUofIRLM7QTBM2G0Ms0dRvG6YsKn0/OhJjJIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T16:27:02Z"
    mac: ENC[AES256_GCM,data:VKtrmBXldyWw2qyMYhbSoyQqs007cjMn6xHtaacgbrAdZUJV9FtXhdIK0NOxRgMt+8j4Va97QmsFEeRCffkK1JtHR89WsfXfvQRqbZi2I+p0X+KSLXmwH4cpg3jX/NjSPnZnnyaUe7LWO7+IadZ/tochDthkIPwvnHTXdnqSOoQ=,iv:J07J0liFvLvASnD5oYFQMKjz6hJ01KPhkfTqRYqHHdQ=,tag:WHyvEwRXcptyAwTYsZAv0w==,type:str]
    version: 3.13.3
