---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-59072dfa-51cf-4f6d-872e-788364554bd2
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
