---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare
spec:
  encryptedData:
    token: AgAEQgWf+lglX6ajOZyMr015ubhTnDlbybzLKdfz+xQeEXCWxLDsl4SQGq5VzxsfnbR9/Eh/XgVdQBMOy/4Eu54SVIRKOjlOLv6yJCour3kJpm+tarASpyTwFUMnsCGjNpJzBrpCSnILy041wuRam13hXWLUc7r1l3w9FLBqd0tovWaV5FcsDY337wMomqacpdbhwwm1kFXep7EYBIyh1V03tpYk21GCTvmP/AnFmCnz5FUMR6p2Y96FElFW8dOrBQZl3hWMd1xi+51pg5CpIZxogcNKzKETxX6c3fHvqxpmlhJoiGNSIN8SS4jbF9+G2PtXcUtmm/NqipViKn+9O1xhmWRuQYIV9WPjynvi22n7HhLvyVHK+ra0mPNYfQBIXaBpQLDTxnUzlKdG0Yz1NqzheLOloWqHeiJVDO6iCEMfHR3WnVuYhqpuAEXZXEw9mk4+OwCIFAX/kcTR+uijOXvkoHeSpZd8ZEqcLudtVMZ+t5+oUI2BJ9Chf1ogvlwkeql7s7z1ZXCMAP7qrDwEy+TUoPXsUq7+PL3KPsu6e3urPZY+C4mqSIYEq86DG/KbUD18nJUKSxGy0xPcc1xZEcQUgdNJkggOH0VjRUG4WUOkFgJB5k3hofk3qJfj12e40LuZU64PVXTJMYJPxhBGCAZpw4OrUXh6PoFXzCT3URLdzuC7epA+Zq/6a8pVizHEOp8uYE7kqug4+VW7pA6uNVin3bwEtZ7mG8N+aUvAGZZxpFDMc+7RPZjr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare
    type: Opaque
