---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: default
spec:
  encryptedData:
    token: AgBocmIgYOFsoC3eISi7Nds+ko9tia6uUGsp3tL7Qv/SH/VTthm6voeOhoAnB8TzLRtIilaKspZAKc6AD/RlsoeXGpbfkccoZ7CqxhlLsy6mz9q8LILz2AWPOzH3jxwh5umszGDGBmI+coCz4mlGF2iTkm3XNJ4hx5JD/gICd+2KsGFxmUPL5POG97AtJDRmGe3hIWS5cKoEDTduw52aNT0jBNsO7AVIq/+Fsl/LQRgo7RR9pWQYCP84nruwR/Houw8U+I5um+bJV9HyK976scDEIyroDXNmKwLTKUrAKrbalUU/pLXrMn+DDCqsis0tn0wxaD74aMqhkwojAw4OzRuQJ2VcmZ7kUW3r18MLxAqM883CouIbv11veGX9XEhX0qYvbyEqWGVensh2i+6D5uSgbnCoTuDaOQr8wO7B53Hj+ulottMVG1mfAmya5K/YfxSUOV8phzL+UX2LIF4oli9afLN7o1FAUjP1f9RaTh8AHALIAMrLGvzj2UYZr5lipF7R1E2/D+sDf6GsPz/6cnlLswxSjj+pVhCoU1RSAMJWpv+ALkk4mOWt3xr6tQNGEtvPZ/JXGgrl4aSUqRZhE52hNt/esCCdC/42nTBafvMj6cq9W7r5U9rbE3rYqxqxCtUOputGNw5e67MdsyH6iO7L9myDKTabdLHZ2HCeM+r06pMBwLp7bHaccR1sfOJbJHwMQ8EFDNLcML6usQM4P+ZEi+HYgY7ld+2pszae7gHYn7s1BF3B8UgC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: default
    type: Opaque
