---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCPUXosIhNZtM1myhzNOR12/bMxrnyUUErFGlu5YnvwzvD6YKimk03d4sJ8kC7DYBKF5c9+qLRN4FUmQgukSQLswNfMSr2OhGjg3/xazSDl/86rass9a9faaqsZmFy0dNun8Nb87gTGOJeljEuYhex7NDEZ9iVZfWG3vt0DPw88UCV8WFZxUt0wgVaTIkd/5dwT8tMGiyKoh8FtbkydS2xeb4W2Bw4/VIEri+tKaW4lNHC0SrdyHZix/+0955weOox4RWHxxjVjlbh0p17uQKuKQPW4+KYR/XOoPOo8TsefnNhQFxnm3irmC4z9gza4N0LDi+ngxQSZXTNFo1Bx/6x9fOEjP8Fdr31X7n+QYnG5jqnprSydq0e8AzgSFesVp9t4MGrMTCQ+Pojt5sT8v7Ea6riBQ38vn7oEyqEAsKQKsQQ/DohtHDLCRtJI4SgOLqHQdUov2JQc38cHQ/8cQomgEa6hcu0wt6Ad3wJz8N5CcmRI3AvF4bmcs9rwjw/euhBAVtXMsgifwsUzcym7Llx8R7/MWqnAKPL6YTc60/lKhEFOqhYu7qrnblFHRsdL3GW4KTsgi7gyaj3AHt2SNaajKMTUUdh/mM+RjNirSJbQ6vCxBjr8BIbVbdulEdfM3J88OooJ5I6fDxqs0CfPhzwWS0r20Y06Wwd4489ZP+Xtd+R7/vpKst3juxMNuTJjNiNWGC+k01lns2p2HYlstMKjvEtZDKxiDz0hFJ6ZNcDWmTbDW0EOo/0X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare
      namespace: cert-manager
    type: Opaque
