---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: meilisearch
  namespace: web
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      enableServiceLinks: true
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:latest
        ports:
          - containerPort: 7700
            name: http
        env:
          - name: MEILI_NO_ANALYTICS
            value: "true"
        volumeMounts:
          - name: hoarder-meilisearch
            mountPath: /meili_data
      volumes:
      - name: hoarder-meilisearch
        persistentVolumeClaim:
          claimName: hoarder-meilisearch-pvc
