---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/sonarr/data
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-tv-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/tv
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-downloads-pv
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/downloads
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
