---
CLUSTER_NAME: production
CLUSTER_DOMAIN: efym.net
TALOS_VERSION: v1.13.8
KUBERNETES_VERSION: v1.36.3
FLUX_VERSION: v2.9.4
CERT_MANAGER_CHART_VERSION: v1.21.1
KUBE_PROMETHEUS_STACK_CHART_VERSION: 81.6.9
LONGHORN_CHART_VERSION: v1.12.0
METALLB_CHART_VERSION: 0.16.1
REFLECTOR_CHART_VERSION: 10.0.63
TRAEFIK_CHART_VERSION: 41.2.0
ALPINE_IMAGE_TAG: latest
AUTHELIA_IMAGE_TAG: latest
BACKREST_IMAGE_TAG: latest
BUSYBOX_IMAGE_TAG: 1.38.0
DEBIAN_IMAGE_TAG: latest
EFYM_NET_IMAGE_TAG: sha-1e91cfe485db4af56600ac1bbd4b3075fa74e6a2
FILEBROWSER_IMAGE_TAG: latest
JELLYFIN_IMAGE_TAG: latest
KARAKEEP_IMAGE_TAG: latest
MEILISEARCH_IMAGE_TAG: v1.13.3
PROWLARR_IMAGE_TAG: develop
QBITTORRENT_IMAGE_TAG: latest
RADARR_IMAGE_TAG: latest
SONARR_IMAGE_TAG: latest
TALOS_API_ADDRESS: 192.168.5.99
GIT_URL: ssh://git@github.com/tw1zr99/lab
GIT_BRANCH: master
GIT_PATH: kubernetes/clusters/production
TALOS_INSTALL_DISK: /dev/sda
NETWORK_PREFIX_LENGTH: "24"
NETWORK_GATEWAY: 192.168.5.1
NETWORK_NAMESERVER_PRIMARY: 192.168.5.1
NETWORK_NAMESERVER_SECONDARY: 1.1.1.1
TRUSTED_LAN_CIDR: 192.168.0.0/16
ACME_DNS_PRIMARY: 1.1.1.1
ACME_DNS_SECONDARY: 9.9.9.9
INGRESS_ADDRESS: 192.168.5.50
NETWORK_BRIDGE: vmbr0
PROXMOX_ENDPOINT: https://hades.lan:8006/
PROXMOX_ISO_DATASTORE: local
PROXMOX_VM_DATASTORE: local-lvm
TALOS_ISO_SHA256: 138138bb8a8b52cea250d53120b708dafc29a70ce2f7145789d9a05cf40bb2d9
VM_CPU_CORES: "4"
VM_MEMORY_MB: "8192"
VM_DISK_SIZE_GB: "100"
STORAGE_HOST: scale.lan
ROUTER_HOST: quack.lan
ADGUARD_PRIMARY_HOST: psi.lan
ADGUARD_SECONDARY_HOST: isp.lan
PROXMOX_PRIMARY_HOST: hades.lan
PROXMOX_SECONDARY_HOST: atlas.lan
NODE_1_NAME: talos-control-01
NODE_1_PROXMOX_HOST: hades
NODE_1_VM_ID: "200"
NODE_1_ADDRESS: 192.168.5.120
NODE_1_MAC_ADDRESS: "02:00:00:05:00:21"
NODE_2_NAME: talos-control-02
NODE_2_PROXMOX_HOST: atlas
NODE_2_VM_ID: "201"
NODE_2_ADDRESS: 192.168.5.121
NODE_2_MAC_ADDRESS: "02:00:00:05:00:22"
NODE_3_NAME: talos-control-03
NODE_3_PROXMOX_HOST: venus
NODE_3_VM_ID: "202"
NODE_3_ADDRESS: 192.168.5.122
NODE_3_MAC_ADDRESS: "02:00:00:05:00:23"
