---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prowlarr-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/appdata/prowlarr/data
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
