---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-tv
spec:
  volumeName: sonarr-tv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-downloads
spec:
  volumeName: sonarr-downloads
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
