---
apiVersion: v1
kind: Service
metadata:
  name: pve1
  namespace: traefik
spec:
  type: ExternalName
  externalName: atlas.lan
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve1
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve1.efym.net`)
      kind: Rule
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: pve1
          port: 80
  tls:
    secretName: efym-net-tls
