---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      enableServiceLinks: true
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.13.3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu:    "100m"
            memory: "128Mi"
          limits:
            cpu:    "250m"
            memory: "256Mi"
        ports:
          - containerPort: 7700
            name: http
        env:
          - name: MEILI_NO_ANALYTICS
            value: "true"
        volumeMounts:
          - name: meilisearch-data
            mountPath: /meili_data
      volumes:
      - name: meilisearch-data
        persistentVolumeClaim:
          claimName: meilisearch-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
  labels:
    app: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      enableServiceLinks: true
      containers:
      - name: karakeep
        image: ghcr.io/karakeep-app/karakeep:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu:    "100m"
            memory: "512Mi"
          limits:
            cpu:    "250m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: TZ
          value: "Europe/London"
        - name: DATA_DIR
          value: "/data"
        - name: DISABLE_SIGNUPS
          value: "false"
        - name: DISABLE_PASSWORD_AUTH
          value: "true"
        - name: NEXTAUTH_URL
          value: "https://links.efym.net"
        - name: NEXTAUTH_URL_INTERNAL
          value: "http://localhost:3000"
        - name: MEILI_ADDR
          value: "http://meilisearch:7700"
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: karakeep
              key: MEILI_MASTER_KEY
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: karakeep
              key: NEXTAUTH_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: karakeep
              key: OPENAI_API_KEY
        # oidc
        - name: OAUTH_WELLKNOWN_URL
          value: "https://login.efym.net/.well-known/openid-configuration"
        - name: OAUTH_CLIENT_ID
          value: "karakeep"
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: karakeep
              key: KARAKEEP_CLIENT_SECRET
        - name: OAUTH_SCOPE
          value: "openid email profile"
        - name: OAUTH_PROVIDER_NAME
          value: "Authelia"
        - name: OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING
          value: "true"
        - name: NEXTAUTH_DEBUG
          value: "true"
        volumeMounts:
        - name: karakeep-data
          mountPath: /data
      volumes:
      - name: karakeep-data
        persistentVolumeClaim:
          claimName: karakeep-data
