---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
spec:
  accessModes:
    - ReadWriteOnce
  # volumeName:
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
spec:
  accessModes:
    - ReadWriteOnce
  # volumeName:
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
