---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: default

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    releaseName: reflector
    namespace: default
