---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-data-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-tv-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-downloads-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
