---
clusterName: ${CLUSTER_NAME}
talosVersion: ${TALOS_VERSION}
kubernetesVersion: ${KUBERNETES_VERSION}
endpoint: https://${TALOS_API_ADDRESS}:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans:
  - ${TALOS_API_ADDRESS}
additionalMachineCertSans:
  - ${TALOS_API_ADDRESS}
nodes:
  - hostname: ${NODE_1_NAME}
    ipAddress: ${NODE_1_ADDRESS}
    controlPlane: true
    installDisk: ${TALOS_INSTALL_DISK}
    nameservers:
      - ${NETWORK_NAMESERVER_PRIMARY}
      - ${NETWORK_NAMESERVER_SECONDARY}
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "${NODE_1_MAC_ADDRESS}"
        dhcp: false
        addresses:
          - ${NODE_1_ADDRESS}/${NETWORK_PREFIX_LENGTH}
        routes:
          - network: 0.0.0.0/0
            gateway: ${NETWORK_GATEWAY}
        vip:
          ip: ${TALOS_API_ADDRESS}
    schematic: &schematic
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools
  - hostname: ${NODE_2_NAME}
    ipAddress: ${NODE_2_ADDRESS}
    controlPlane: true
    installDisk: ${TALOS_INSTALL_DISK}
    nameservers:
      - ${NETWORK_NAMESERVER_PRIMARY}
      - ${NETWORK_NAMESERVER_SECONDARY}
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "${NODE_2_MAC_ADDRESS}"
        dhcp: false
        addresses:
          - ${NODE_2_ADDRESS}/${NETWORK_PREFIX_LENGTH}
        routes:
          - network: 0.0.0.0/0
            gateway: ${NETWORK_GATEWAY}
        vip:
          ip: ${TALOS_API_ADDRESS}
    schematic: *schematic
  - hostname: ${NODE_3_NAME}
    ipAddress: ${NODE_3_ADDRESS}
    controlPlane: true
    installDisk: ${TALOS_INSTALL_DISK}
    nameservers:
      - ${NETWORK_NAMESERVER_PRIMARY}
      - ${NETWORK_NAMESERVER_SECONDARY}
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "${NODE_3_MAC_ADDRESS}"
        dhcp: false
        addresses:
          - ${NODE_3_ADDRESS}/${NETWORK_PREFIX_LENGTH}
        routes:
          - network: 0.0.0.0/0
            gateway: ${NETWORK_GATEWAY}
        vip:
          ip: ${TALOS_API_ADDRESS}
    schematic: *schematic
patches:
  - "@./patches/longhorn.yaml"
