---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gatus-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
