---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: efym-net
  namespace: default
spec:
  secretName: efym-net-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  commonName: "*.efym.net"
  dnsNames:
  - "efym.net"
  - "*.efym.net"
