---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: token
        selector:
          dnsZones:
            - "efym.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: efym-net
  namespace: cert-manager
spec:
  secretName: efym-net-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  commonName: "*.efym.net"
  dnsNames:
  - "efym.net"
  - "*.efym.net"
