---
apiVersion: v1
kind: Service
metadata:
  name: kanidm
  namespace: kanidm
spec:
  selector:
    app: kanidm
  ports:
    - name: https
      port: 443
      targetPort: 8443
    - name: ldap
      port: 636
      targetPort: 3636
---
kind: Service
apiVersion: v1
metadata:
  name: authelia
  namespace: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: http
    port: 9091
    targetPort: 9091
    protocol: TCP
