---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: qbittorrent

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
