---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: qbittorrent-downloads
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/downloads
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
