---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-downloads
spec:
  volumeName: qbittorrent-downloads
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
