apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:HVA8cihIg9jdN67zd0WGLIylre8PvmA/DluJYlTnZIzjuNnAinsXAyeBuPSrpxA9swkmKz9F+W8sOAL0TNOLa5mEyAOrNn3Urbi76DYjugCmgsxeXTzJhPA3WWpKEZD0lTCnWb2tJWj+cKWX3ti0neuYkCoRsBTk57xWoAluW69TVQ9Pi3PcBDY5u0do7NCyoakvpQ/xejRkHD4g2vOAjJ3wgj+SnzNj03uaeIikpfnkw8FzxjVrQxiMXdehta7mPYdF31eSBcEaFgbqgjr4d8cuiixvjTsbba+kRUan37R/vPwO4SYUUHBe66I1c437ZuTTdI3hS2xUNb3KDA==,iv:MaH4ahL1NzQx8oGA+H6J6ZqGeCXH/lS3bdyy2Vu883A=,tag:lmSDJcT3wk1O2CNpdIkd2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNXhDTkg0Umxqb2sxNGJa
            bmgzeWFHV2dwRDBxWm5qRW1XT3BIZ0VURm53CkVpRG5jUzNSM2U3WUI2QjZyKzB6
            WnlaVTVoNHpXYm83bHg0T2FVSzAyUlUKLS0tIHNId05iQkZRYVlmVGNSelllM2xC
            Rjd1Z2pxMFMwdGF2UTZTQ1pBbUhyNTAKJ7dyxqj3bsef8bxgGw769nxN9lLH6TzV
            2sgHOE+Ln5aFffpIdCsreOF8WXSNNx4VyaK4x5YQH1v5I/p0aOa1Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T03:33:37Z"
    mac: ENC[AES256_GCM,data:ZUe4eq8DMX+f4lkZVOJV3SGL0r0vCzwyVUWKOlqAIXqseyoRvQHCTkSjKfSCbn22aNHWpyQ26VEczionId/q+bzKBMDov+CwSeSd37QTFTThtJHkQ2757Xy8hwZERknkwyOuV52XVZM7pXUSJv+g8xZlok9m5Mu7ll/1uPopivg=,iv:S7HDj0/NFTeskzboMc89fBsWX/Cl0F5IFTZN+VVvSXY=,tag:jhtJr5Bp+aN8b5xBHgbQzw==,type:str]
    version: 3.13.3
