---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-data
  namespace: kanidm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
