---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1h0m0s
  install:
    createNamespace: true
  chart:
    spec:
      chart: openebs
      version: "4.3.2"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
    engines:
      jiva:
        enabled: false
      cstor:
        enabled: false
      replicated:
        mayastor:
          enabled: true
    lvm-localpv:
      enabled: false
    zfs-localpv:
      enabled: false
    hostpath-localpv:
      enabled: false
    localpv-provisioner:
      enabled: false
