---
kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tw1zr@efym.net
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: tw1zr@efym.net
            apiTokenSecretRef:
              name: cloudflare
              key: token
        selector:
          dnsZones:
            - "efym.net"
