---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
  - sealedsecret.yaml
  - issuer.yaml
  - certificate.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: 1.9.1
    valuesFile: values.yaml
