---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/movies
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-tv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/tv
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-channels
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/channels
    server: 192.168.5.3
  persistentVolumeReclaimPolicy: Retain
