---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-movies
spec:
  volumeName: jellyfin-movies
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-tv
spec:
  volumeName: jellyfin-tv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-channels
spec:
  volumeName: jellyfin-channels
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
