---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: sonarr-tv
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: sonarr-downloads
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
