name: ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  terraform-fmt:
    name: terraform-fmt  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: check formatting
        working-directory: terraform
        run: terraform fmt -check -recursive

  terraform-validate:
    name: terraform-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: init
        working-directory: terraform
        run: terraform init -backend=false

      - name: validate
        working-directory: terraform
        run: terraform validate

  terraform-tfsec:
    name: terraform-tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform

  kubernetes-kubeconform:
    name: kubernetes-kubeconform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.47.1

      - name: install kubeconform
        run: |
          curl -sL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar xz
          chmod +x kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: build and validate overlays
        run: |
          for k in $(find kubernetes -type f -name kustomization.yaml); do
            dir=$(dirname "$k")
            kustomize build "$dir"
            echo "---"
          done \
            | yq eval-all 'del(.sops)' - \
            | kubeconform \
                --strict \
                --ignore-missing-schemas \
                --schema-location default

  kubernetes-kube-linter:
    name: kubernetes-kube-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stackrox/kube-linter-action@v1.0.7
        with:
          directory: kubernetes
          config: .kube-linter.yaml
          format: plain
          output-file: kube-linter.log

  # kubernetes-kube-score:
  #   name: kubernetes-kube-score
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: syntaqx/setup-kustomize@v1
  #     - uses: mikefarah/yq@v4.47.1
  #
  #     - name: make temp output directory
  #       run: mkdir -p out/kustomize
  #
  #     - name: kustomize build to standard template
  #       run: |
  #         for k in $(find kubernetes -type f -name kustomization.yaml); do
  #           dir=$(dirname "$k")
  #           kustomize build "$dir"
  #           echo "---"
  #         done \
  #           | yq eval-all 'del(.sops)' - \
  #           > out/kustomize/built.yaml
  #
  #     - name: kube-score check
  #       uses: piraces/kube-score-ga@v0.1.3
  #       with:
  #         manifests-folders: './out/kustomize/*.yaml'
