name: ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  terraform-fmt:
    name: terraform-fmt  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: check formatting
        working-directory: terraform
        run: terraform fmt -check -recursive

  terraform-validate:
    name: terraform-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: init
        working-directory: terraform
        run: terraform init -backend=false

      - name: validate
        working-directory: terraform
        run: terraform validate

  terraform-tfsec:
    name: Terraform security scan (tfsec)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1
        with:
          directory: terraform

  kubernetes-kubeconform:
    name: kubernetes-kubeconform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install kubeconform
        run: |
          curl -sL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar xz
          chmod +x kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: install yq
        run: |
          wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: build and validate overlays
        run: |
          # Build each overlay, separate documents with '---'
          for k in $(find kubernetes -type f -name kustomization.yaml); do
            dir=$(dirname "$k")
            echo "### Overlay $dir ###"
            kustomize build "$dir"
            echo "---"
          done \
            | yq eval-all 'del(.sops)' - \
            | kubeconform \
                --strict \
                --ignore-missing-schemas \
                --schema-location default

  kubernetes-kubelinter:
    name: kubernetes-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: scan with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: kubernetes
          format: json
          output-file: kube-linter.json

  kubernetes-kubescore:
    name: kubernetes-score
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: kube-score check
        uses: piraces/kube-score-ga@v0.1.3
        with:
          manifests-folders: './kubernetes/**/*.yaml'
