name: terraform

on:
  pull_request:

permissions:
  contents: read

jobs:
  terraform-fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Check formatting
        working-directory: terraform
        run: terraform fmt -check -recursive

  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: terraform-fmt
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Init (no backend)
        working-directory: terraform
        run: terraform init -backend=false

      - name: Validate config
        working-directory: terraform
        run: terraform validate
