name: terraform

on:
  pull_request:

permissions:
  contents: read

jobs:
  # 1. Ensure all Terraform code is formatted
  terraform-fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Check formatting
        working-directory: terraform
        run: terraform fmt -check -recursive
        # terraform fmt -check enforces canonical formatting :contentReference[oaicite:0]{index=0} :contentReference[oaicite:1]{index=1}

  # 2. Validate Terraform configuration
  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: terraform-fmt
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Init (no backend)
        working-directory: terraform
        run: terraform init -backend=false
      - name: Validate config
        working-directory: terraform
        run: terraform validate

  # 3. Generate a plan and upload for review
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Init
        working-directory: terraform
        run: terraform init -input=false
      - name: Plan
        working-directory: terraform
        run: terraform plan -out=tfplan -input=false
      - name: Upload plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform/tfplan
